fix: No module named 'scripts.generate_pyi'
When run `install.sh` directly, it will fail with
the following error:

```bash
Traceback (most recent call last):
  File "DeepGEMM/setup.py", line 19, in <module>
    from scripts.generate_pyi import generate_pyi_file
ModuleNotFoundError: No module named 'scripts.generate_pyi'
```

This is because the `scripts/` directory has no `__init__.py`,
so Python can't import it as a package. The fix is to create one.

Signed-off-by: Hollow Man <hollowman@opensuse.org>